scss_files: 'Website/AtariLegend/themes/styles/**/scss/*.css.scss'

linters:
    BorderZero:
        enabled: false

    Indentation:
        width: 4

    SelectorFormat:
        enabled: true
        convention: snake_case
    IdSelector:
        enabled: false
    PropertySortOrder:
        enabled: false
