linters:
    BorderZero:
        enabled: false
    Indentation:
        width: 4
    SelectorFormat:
        enabled: true
        convention: snake_case
    IdSelector:
        enabled: false
    PropertySortOrder:
        enabled: false
    EmptyLineBetweenBlocks:
        enabled: false
    ColorVariable:
        enabled: false
    SelectorFormat:
        enabled: false
    HexLength:
        style: long
    NameFormat:
        enabled: true
        convention: snake_case
    PlaceholderInExtend:
        enabled: false
    SingleLinePerSelector:
        enabled: false
