version: '3'
services:
  # Database instance
  db:
    image: mysql:5
    environment:
      MYSQL_ROOT_PASSWORD: atari
    volumes:
      - ./db:/var/lib/mysql
      # Need special MySQL config to disable `only_full_group_by`
      - ./mysqld.cnf:/etc/mysql/conf.d/mysqld.cnf
  # PHP instance
  php:
    # Custom image as we need specific extensions
    build: ./php
    links:
      - db
    ports:
      - 80:80
    volumes:
      - ../Website/AtariLegend:/var/www/html
    depends_on:
      - php-composer
  # PHP Composer
  php-composer:
    build: ./php
    volumes:
      - ../Website/AtariLegend/php:/php
    command: bash -c "composer.phar install -d /php; composer.phar update -d /php"
  # Convenience image to run Grunt
  nodejs:
    build: ./php
    volumes:
      - ../:/app
    working_dir: /app
    command: bash -c "npm install; npm rebuild node-sass; npm run grunt; npm run grunt -- watch"
  # Convenience phpMyAdmin image to administer the database
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      UPLOAD_LIMIT: 8M
    links:
      - db:db
    ports:
      - 8080:80
