name: Build
on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache Docker layers
        uses: satackey/action-docker-layer-caching@v0.0.4

      - name: Build Docker image
        run: docker build -t atari-legend Docker/php/

      - name: Cache node_modules/
        uses: actions/cache@v2
        env:
            cache-name: cache-node-modules
        with:
          path: node_modules/
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-#

      - name: Install NPM modules
        run: docker run -v $PWD:/data -w /data atari-legend npm install

      - name: Install Composer dependencies
        run: docker run -v $PWD:/data atari-legend composer install -d /data/public/php/

      - name: Run Grunt
        run: docker run -v $PWD:/data -w /data atari-legend npm run grunt

      # Preserve generated files (e.g. style.css) for the next workflow steps
      - name: Save generated files
        uses: actions/upload-artifact@v2
        with:
          name: website
          path: public/

  deploy-dev:
    name: Deploy development
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/development'
    steps:
      - uses: actions/checkout@v2
      # Restore generated files from previous step
      - uses: actions/download-artifact@v2
        with:
          name: website
          path: public/
      - name: Deploy
        run: |
          eval "$(ssh-agent -s)"
          ssh-add - <<< "${{ secrets.DEPLOY_SSH_KEY }}"
          ./.github/workflows/deploy.sh "${{ secrets.DEV_DEPLOY_USER }}" "${{ secrets.DEV_DEPLOY_HOST }}" "${{ secrets.DEV_DEPLOY_PATH }}"

  deploy-prototype:
    name: Deploy inside the Laravel prototype
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/development'
    steps:
      - uses: actions/checkout@v2
      # Restore generated files from previous step
      - uses: actions/download-artifact@v2
        with:
          name: website
          path: public/
      - name: Adjust .htaccess files to run inside the prototype folder
        run: |
          mv -f public/.htaccess.prototype public/.htaccess
          rm -f public/php/.htaccess
      - name: Deploy
        run: |
          eval "$(ssh-agent -s)"
          ssh-add - <<< "${{ secrets.DEPLOY_SSH_KEY }}"
          ./.github/workflows/deploy.sh "${{ secrets.DEV_DEPLOY_PROTOTYPE_USER }}" "${{ secrets.DEV_DEPLOY_PROTOTYPE_HOST }}" "${{ secrets.DEV_DEPLOY_PROTOTYPE_PATH }}"

  deploy-prod:
    name: Deploy production
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v2
      # Restore generated files from previous step
      - uses: actions/download-artifact@v2
        with:
          name: website
          path: public/
      - name: Deploy
        run: |
          eval "$(ssh-agent -s)"
          ssh-add - <<< "${{ secrets.DEPLOY_SSH_KEY }}"
          ./.github/workflows/deploy.sh "${{ secrets.PROD_DEPLOY_USER }}" "${{ secrets.PROD_DEPLOY_HOST }}" "${{ secrets.PROD_DEPLOY_PATH }}"
